// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSI_Ecommerce.Context;

namespace PSI_Ecommerce.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20201106001047_CreateEcommerceBD")]
    partial class CreateEcommerceBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PSI_Ecommerce.Models.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<string>("TituloAnuncio");

                    b.Property<int?>("UsuarioIdUsuario");

                    b.Property<double>("Valor");

                    b.HasKey("IdAnuncio");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Anuncio");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnuncioIdAnuncio");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nota");

                    b.Property<int?>("UsuarioIdUsuario");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("AnuncioIdAnuncio");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnuncioIdAnuncio");

                    b.Property<int?>("ComentarioPaiIdComentario");

                    b.Property<string>("Descricao");

                    b.Property<int?>("UsuarioIdUsuario");

                    b.HasKey("IdComentario");

                    b.HasIndex("AnuncioIdAnuncio");

                    b.HasIndex("ComentarioPaiIdComentario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Contato", b =>
                {
                    b.Property<int>("IdContato")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TelefoneFixo");

                    b.Property<string>("TelefoneMovel");

                    b.Property<int?>("UsuarioIdUsuario");

                    b.HasKey("IdContato");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Foto", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnuncioIdAnuncio");

                    b.Property<byte[]>("Imagem");

                    b.Property<int?>("UsuarioIdUsuario");

                    b.HasKey("IdFoto");

                    b.HasIndex("AnuncioIdAnuncio");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.Property<string>("Username");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Anuncio", b =>
                {
                    b.HasOne("PSI_Ecommerce.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Avaliacao", b =>
                {
                    b.HasOne("PSI_Ecommerce.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioIdAnuncio");

                    b.HasOne("PSI_Ecommerce.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Comentario", b =>
                {
                    b.HasOne("PSI_Ecommerce.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioIdAnuncio");

                    b.HasOne("PSI_Ecommerce.Models.Comentario", "ComentarioPai")
                        .WithMany()
                        .HasForeignKey("ComentarioPaiIdComentario");

                    b.HasOne("PSI_Ecommerce.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Contato", b =>
                {
                    b.HasOne("PSI_Ecommerce.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });

            modelBuilder.Entity("PSI_Ecommerce.Models.Foto", b =>
                {
                    b.HasOne("PSI_Ecommerce.Models.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioIdAnuncio");

                    b.HasOne("PSI_Ecommerce.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
